### PR TITLE
[UI]: Navbar bg change

### LINKED ISSUE #33: [UI]: Navbar background change
Hello! The text on navbar is not visible when we scroll. So please assign me this issue, I will add some background to navbar and make it user friendly!
Please assign me under hacktoberfest.

### PR DESCRIPTION
**Pull request by sanjeevani-25**
closes #33
This is the final look.

Screenshot (445)
Screenshot (446)

### CODE REVIEW

**Comment by dakshsinghrathore** [comment]
it isn't matching up with the design flow, can you come up with something better ?

**Review by dakshsinghrathore — CHANGES_REQUESTED** [review]
It isn't fitting in with every page, kindly suggest some new designs which matches up with current design flow !

**Comment by sanjeevani-25** [comment]
How about this? @dakshsinghrathore 

image
image

**Comment by dakshsinghrathore** [comment]
> How about this? @dakshsinghrathore
> 
> image image

Lgtm, kindly create a fresh PR ! will review it and merge it shortly !

**Pull request closed without merging**
