### PR TITLE
Feat: added the feature menu vertical navbar

### PR DESCRIPTION
**Pull request by ankushtripathii**
This PR  Added the new vertical navbar that includes (launches, missions, updates, and careers)

### CODE REVIEW

**Comment by dakshsinghrathore** [comment]
@ankushtripathii looks great, but a small change is required i.e **CENTER THE UNDERLINE**
image

**Comment by ankushtripathii** [comment]
I think that is a bug because I have not added the underline property  this I coded {text-decoration: none}

**Comment by dakshsinghrathore** [comment]
Thanks for contributing @ankushtripathii , stick around as i have some special gifts from my side for the top 3 contributors on my repo, kindly star the repo and a follow on github will be much appreciated !!🙌🏽

**Review by dakshsinghrathore — COMMENTED** [review]
lgtm !

**Pull request merged**
