### PR TITLE
Replaced 3 blurred photos with high quality AI generated photos

### PR DESCRIPTION
**Pull request by ankit9958**

### CODE REVIEW

**Review by dakshsinghrathore — APPROVED** [review]
lgtm !!

**Comment by ankit9958** [comment]
Thanks!

**Comment by dakshsinghrathore** [comment]
@ankit9958 Hey man it would be great if you dropped a follow on this acc and star to this repo ! Happy Coding !😀🤝

**Comment by ankit9958** [comment]
@dakshsinghrathore  done 😊

**Pull request merged**
