### PR TITLE
fix: back to top button

### PR DESCRIPTION
**Pull request by PrathameshSonje**
#126 
This PR fixes issue #126

### CODE REVIEW

**Comment by PrathameshSonje** [comment]
It kind of glitches when pressed

**Comment by dakshsinghrathore** [comment]
> It kind of glitches when clicked. I can update the smoothScrollToTop() function

go ahead and do it !

**Comment by PrathameshSonje** [comment]
I have made changes to the function, Now it works as expected
[screen-capture.webm](https://github.com/dakshsinghrathore/ISRO-web/assets/111238447/912c259b-2fac-4684-bc89-cd9c01bff433)

**Comment by dakshsinghrathore** [comment]
@PrathameshSonje The PR #132 seems more smooth and reliable, will merge it instead, you can work on some other issues, stick around you will be assigned next one's fs

**Pull request closed without merging**
