### PR TITLE
Sir I have made the changes the bottom to top button is now working you can check now  

### PR DESCRIPTION
**Pull request by AdityaGaur7**
https://github.com/dakshsinghrathore/ISRO-web/assets/121216575/1586c41f-117a-4ee9-8fe6-418be0bf55be

### CODE REVIEW

**Comment by dakshsinghrathore** [comment]
@AdityaGaur7 will review it soon !

**Review by dakshsinghrathore — APPROVED** [review]
lgtm !!

**Comment by AdityaGaur7** [comment]
thank you sir , feeling pleased to know that

**Comment by dakshsinghrathore** [comment]
@AdityaGaur7 would be really great if you drop a star on this repo and a follow on my acc. follow back is assured 😉

**Comment by AdityaGaur7** [comment]
Of Course sir , It will be my pleasure to connect with you

**Pull request merged**
