### PR TITLE
Final Changes

### PR DESCRIPTION
**Pull request by Smitkhobragade**

### CODE REVIEW

**Review by dakshsinghrathore — CHANGES_REQUESTED** [review]
I appreciate your sincere dedication towards this repo ! I just merged a PR due to which your PR is showing some merge conflicts, kindly resolve it and will soon merge it asap !

**Comment by dakshsinghrathore** [comment]
@Smitkhobragade

**Comment by Smitkhobragade** [comment]
I have Resolved the Conflicts now you can merge into main

**Review by dakshsinghrathore — COMMENTED** [review]
lgtm !!

**Pull request merged**
