### PR TITLE
Center arrow

### PR DESCRIPTION
**Pull request by Iamdivyak**
issue no: #67

### CODE REVIEW

**Comment by Iamdivyak** [comment]
hey @dakshsinghrathore while going throw your codes in index.html. I saw that the div with the class name scroll-arrow (the arrow div) is written twice in all sections. it will work as it is, after removing that repetitive code.

image

should I make a new issue for refactoring the codes?

**Review by dakshsinghrathore — APPROVED** [review]
lgtm !!

**Comment by dakshsinghrathore** [comment]
> hey @dakshsinghrathore while going throw your codes in index.html. I saw that the div with the class name scroll-arrow (the arrow div) is written twice in all sections. it will work as it is, after removing that repetitive code.
> 
> image
> 
> should I make a new issue for refactoring the codes?

Yeah I was about to create an issue on refactoring of the whole code where necessary !
Kindly create one, and will  assign it to you asap ! Thanks for your patience !

**Comment by Iamdivyak** [comment]
> > hey @dakshsinghrathore while going throw your codes in index.html. I saw that the div with the class name scroll-arrow (the arrow div) is written twice in all sections. it will work as it is, after removing that repetitive code.
> > image
> > should I make a new issue for refactoring the codes?
> 
> Yeah I was about to create an issue on refactoring of the whole code where necessary ! Kindly create one, and will assign it to you asap ! Thanks for your patience !

hear, issue no: #83

**Pull request merged**
