### PR TITLE
feat/isro favicon

### LINKED ISSUE #32: [FEAT]: Favicon missing
The [live](https://dsr-isrowebapp.netlify.app/) link of this repo lacks favicon, kindly implement ISRO icon as the favicon !

### PR DESCRIPTION
**Pull request by pankaj-2503**
### What does this PR introduces ?
In  this  PR  a new features is added that is the favicon of isro for its originality .

### Why this is needed
As it helps identify the website quickly , improves branding and look more professional.
Fixes  #32

### CODE REVIEW

**Review by dakshsinghrathore — CHANGES_REQUESTED** [review]
no changes visible !

**Comment by pankaj-2503** [comment]
You mean the changes that is the favicon is missing .

**Comment by pankaj-2503** [comment]
I am not understanding what are you trying to say please elaborate like the favicon is not showing clearly or something like that. what ever the problem is

**Review by dakshsinghrathore — COMMENTED** [review]
Still it isn't visible ! I think you should leave this for now and start working on some other issues by then I will look into this and inform you shortly

**Pull request closed without merging**
