### PR TITLE
feat: updated font to SpaceX like

### PR DESCRIPTION
**Pull request by psworld**
Fixed: #43 

Updated website font to SpaceX like.

New font is looking a lot better and clean.

Comparing old font vs new font below:

### Old font

image

### New font
image

### CODE REVIEW

**Comment by psworld** [comment]
@dakshsinghrathore Hello, 

Kindly review my PR. I have changed the font to [spaceX like](https://fonts.google.com/specimen/Familjen+Grotesk?query=grotesk) which was mentioned by you in the comments of issue.

If there are any more changes required please let me know.

and If everything is right then please merge my PR.

**Review by dakshsinghrathore — CHANGES_REQUESTED** [review]
fix the font size too !!

**Comment by psworld** [comment]
Hey @dakshsinghrathore ,

I have fixed the font size to match with the previous font-style as you suggested.

Please review the changes.

**Review by dakshsinghrathore — APPROVED** [review]
lgtm !!

**Pull request merged**
